// NAVIGATION
export const NAV_LINKS = [
  { href: '/', key: 'produtcs', label: 'المنتجات' },
  { href: '/', key: 'home', label: 'الرئيسية' }
]

// WILAYAS (states)
export const WILAYAS = [
  { name: 'أدرار', value: 'Adrar' },
  { name: 'الشلف', value: 'Chlef' },
  { name: 'الأغواط', value: 'Laghouat' },
  { name: 'أم البواقي', value: 'Oum-El-Bouaghi' },
  { name: 'باتنة', value: 'Batna' },
  { name: 'بجاية', value: 'Béjaïa' },
  { name: 'بسكرة', value: 'Biskra' },
  { name: 'بشار', value: 'Béchar' },
  { name: 'البليدة', value: 'Blida' },
  { name: 'البويرة', value: 'Bouira' },
  { name: 'تمنراست', value: 'Tamanrasset' },
  { name: 'تبسة', value: 'Tébessa' },
  { name: 'تلمسان', value: 'Tlemcen' },
  { name: 'تيارت', value: 'Tiaret' },
  { name: 'تيزي وزو', value: 'Tizi-Ouzou' },
  { name: 'الجزائر', value: 'Algiers' },
  { name: 'الجلفة', value: 'Djelfa' },
  { name: 'جيجل', value: 'Jijel' },
  { name: 'سطيف', value: 'Sétif' },
  { name: 'سعيدة', value: 'Saïda' },
  { name: 'سكيكدة', value: 'Skikda' },
  { name: 'سيدي بلعباس', value: 'Sidi-Bel-Abbès' },
  { name: 'عنابة', value: 'Annaba' },
  { name: 'قالمة', value: 'Guelma' },
  { name: 'قسنطينة', value: 'Constantine' },
  { name: 'المدية', value: 'Médéa' },
  { name: 'مستغانم', value: 'Mostaganem' },
  { name: 'المسيلة', value: 'Msila' },
  { name: 'معسكر', value: 'Mascara' },
  { name: 'ورقلة', value: 'Ouargla' },
  { name: 'وهران', value: 'Oran' },
  { name: 'البيض', value: 'El-Bayadh' },
  { name: 'إليزي', value: 'Illizi' },
  { name: 'برج بوعريريج', value: 'Bordj-Bou-Arreridj' },
  { name: 'بومرداس', value: 'Boumerdès' },
  { name: 'الطارف', value: 'El-Tarf' },
  { name: 'تندوف', value: 'Tindouf' },
  { name: 'تيسمسيلت', value: 'Tissemsilt' },
  { name: 'الوادي', value: 'El-Oued' },
  { name: 'خنشلة', value: 'Khenchela' },
  { name: 'سوق أهراس', value: 'Souk-Ahras' },
  { name: 'تيبازة', value: 'Tipaza' },
  { name: 'ميلة', value: 'Mila' },
  { name: 'عين الدفلى', value: 'Aïn-Defla' },
  { name: 'النعامة', value: 'El-Naâma' },
  { name: 'عين تموشنت', value: 'Aïn-Témouchent' },
  { name: 'غرداية', value: 'Ghardaïa' },
  { name: 'غليزان', value: 'Relizane' },
  { name: 'تيميمون', value: 'Timimoun' },
  { name: 'برج باجي مختار', value: 'Bordj-Baji-Mokhtar' },
  { name: 'أولاد جلال', value: 'Ouled-Djellal' },
  { name: 'بني عباس', value: 'Béni-Abbès' },
  { name: 'عين صالح', value: 'Aïn-Salah' },
  { name: 'عين قزام', value: 'Aïn-Guezzam' },
  { name: 'تقرت', value: 'Touggourt' },
  { name: 'جانت', value: 'Djanet' },
  { name: 'المغير', value: 'El-Meghaier' },
  { name: 'المنيعة', value: 'El-Menia' }
]
